[08 Nov 2021, 1:26:37 pm] [Valinor GameThread] [TaskManager] [ERROR] Catching
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:373) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.valinor.game.content.announcements.dyk.DidYouKnowTask.execute(DidYouKnowTask.java:52) ~[Valinor-S/:?]
	at com.valinor.game.task.Task.sequence(Task.java:240) ~[Valinor-S/:?]
	at com.valinor.game.task.TaskManager.sequence(TaskManager.java:51) ~[Valinor-S/:?]
	at com.valinor.game.world.World.lambda$new$2(World.java:269) ~[Valinor-S/:?]
	at com.valinor.game.world.entity.Mob.time(Mob.java:1548) [Valinor-S/:?]
	at com.valinor.game.world.World.sequence(World.java:413) [Valinor-S/:?]
	at com.valinor.game.GameEngine.run(GameEngine.java:213) [Valinor-S/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
